# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fibs_recursive(num, term1 = 1, term2 = 2, sum = 2)
  
  next_term = term1 + term2
  return sum if next_term >= num

  sum += next_term if next_term % 2 == 0

  even_fibs_recursive(num, term2, next_term, sum)

end

# even_fibs_recursive(89)
puts even_fibs_recursive(4000000)