# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fibs(num)

	lower = 1
	upper = 2

	sum = 0

	while true do
		curr = upper
		# puts "CURR: #{curr}"
		if curr > num
			break
		elsif curr % 2 == 0
			sum += curr
			# puts "SUM: #{sum}"
		end
		upper = lower + curr
		lower = curr
	end
	sum
end

puts even_fibs(4000000)

